[2024-09-25T13:37:58.470+0200] {processor.py:186} INFO - Started process (PID=64572) to work on /home/isi/airflow/dags/predict_model_dag.py
[2024-09-25T13:37:58.470+0200] {processor.py:914} INFO - Processing file /home/isi/airflow/dags/predict_model_dag.py for tasks to queue
[2024-09-25T13:37:58.472+0200] {logging_mixin.py:190} INFO - [2024-09-25T13:37:58.471+0200] {dagbag.py:588} INFO - Filling up the DagBag from /home/isi/airflow/dags/predict_model_dag.py
[2024-09-25T13:37:58.477+0200] {logging_mixin.py:190} INFO - [2024-09-25T13:37:58.476+0200] {dagbag.py:387} ERROR - Failed to import: /home/isi/airflow/dags/predict_model_dag.py
Traceback (most recent call last):
  File "/home/isi/miniconda3/envs/lfb_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/isi/airflow/dags/predict_model_dag.py", line 3, in <module>
    from airflow.providers.mongo.hooks.mongo import MongoHook
ModuleNotFoundError: No module named 'airflow.providers.mongo'
[2024-09-25T13:37:58.477+0200] {processor.py:927} WARNING - No viable dags retrieved from /home/isi/airflow/dags/predict_model_dag.py
[2024-09-25T13:37:58.499+0200] {processor.py:208} INFO - Processing /home/isi/airflow/dags/predict_model_dag.py took 0.035 seconds
